# Generated by Django 5.0.7 on 2025-08-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
                ('country_code', models.CharField(max_length=20, verbose_name='Country Code')),
                ('country_slug', models.SlugField(default='default-slug', max_length=100)),
                ('country_description', models.TextField()),
                ('continent', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdeyByNameDscCountry',
            fields=[
            ],
            options={
                'verbose_name': 'My Country',
                'verbose_name_plural': 'My Countries',
                'ordering': ['-country_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('country.country',),
        ),
        migrations.CreateModel(
            name='CountryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
            options={
                'verbose_name': 'Country Detail',
                'verbose_name_plural': 'Country Details',
            },
        ),
    ]
