# Generated by Django 5.2.4 on 2025-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
                ('country_code', models.CharField(max_length=20, verbose_name='Country Code')),
                ('country_slug', models.SlugField(default='default-slug', max_length=100)),
                ('country_description', models.TextField()),
            ],
        ),
    ]
