# Generated by Django 5.2.4 on 2025-08-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_countrydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydetail',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='country.country'),
        ),
    ]
