# Generated by Django 5.2.4 on 2025-08-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='parent_topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_toppings', to='topping.topping'),
        ),
    ]
