GET http://127.0.0.1:8080/product/ HTTP/1.1

###


POST http://127.0.0.1:8080/product/ HTTP/1.1
Content-Type: application/json

{
    "product_name": "New Product",
    "selling_price": 19.99,
    "purchase_price": 15.00,
    "product_code": "NP12345"
}