# Generated by Django 5.0.7 on 2025-08-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('lock_product', 'Can lock product'), ('approve_product', 'Can approve product')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
