# Generated by Django 5.0.7 on 2025-10-09 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyentry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-entry_date', '-created_at'], 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='created_time',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date this entry is about'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='entry_time',
            field=models.TimeField(blank=True, help_text='Specific time of day for the entry', null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive old entries'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin important entries'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diaryentryshare',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diaryentryshare',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User-specific tag (null for global tags)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='diary_attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('neutral', 'Neutral'), ('excited', 'Excited'), ('tired', 'Tired'), ('productive', 'Productive'), ('grateful', 'Grateful'), ('reflective', 'Reflective'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='mood_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 scale', null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='diary_entries', to='dairyentry.tag'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diaryentryshare',
            name='diary_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='dairyentry.diaryentry'),
        ),
        migrations.AlterField(
            model_name='diaryentryshare',
            name='permission',
            field=models.CharField(choices=[('read', 'Read Only'), ('comment', 'Can Comment')], default='read', max_length=10),
        ),
        migrations.AlterField(
            model_name='diaryentryshare',
            name='shared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'user')},
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('milestone', 'Milestone'), ('project', 'Project'), ('travel', 'Travel'), ('relationship', 'Relationship'), ('health', 'Health'), ('education', 'Education'), ('career', 'Career'), ('personal', 'Personal'), ('goal', 'Goal'), ('habit', 'Habit'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing events', null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for timeline visualization', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon/emoji for UI', max_length=50, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('is_milestone', models.BooleanField(default=False, help_text='Mark as major milestone')),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='dairyentry.timelineevent')),
                ('tags', models.ManyToManyField(blank=True, related_name='timeline_events', to='dairyentry.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('checkpoint_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='dairyentry.diaryentry')),
                ('timeline_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='dairyentry.timelineevent')),
            ],
            options={
                'ordering': ['checkpoint_date'],
            },
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='timeline_event',
            field=models.ForeignKey(blank=True, help_text='Optional timeline event this diary entry belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='dairyentry.timelineevent'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['user', 'entry_date'], name='dairyentry__user_id_120120_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['user', 'is_pinned', 'is_archived'], name='dairyentry__user_id_0c740c_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['mood'], name='dairyentry__mood_676d97_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['timeline_event'], name='dairyentry__timelin_9b2572_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['user', 'start_date'], name='dairyentry__user_id_396869_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['user', 'event_type'], name='dairyentry__user_id_ba6910_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['status'], name='dairyentry__status_1b4032_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['parent_event'], name='dairyentry__parent__b88328_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinecheckpoint',
            index=models.Index(fields=['timeline_event', 'checkpoint_date'], name='dairyentry__timelin_63500b_idx'),
        ),
    ]
