# Generated by Django 5.0.7 on 2025-10-10 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyentry', '0002_alter_diaryentry_options_alter_tag_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='health_status',
            field=models.JSONField(blank=True, help_text='Health tracking: sleep_hours, exercise_minutes, energy_level, symptoms, etc.', null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='productive_work_list',
            field=models.JSONField(blank=True, help_text='List of productive tasks/accomplishments for the day', null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='quote',
            field=models.TextField(blank=True, help_text='Inspiring quote of the day', null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='word_of_day',
            field=models.CharField(blank=True, help_text='Interesting word learned today', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='content',
            field=models.TextField(blank=True, help_text='Legacy content field - use EventContent for timeline-based entries', null=True),
        ),
        migrations.CreateModel(
            name='EventContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_datetime', models.DateTimeField(help_text='Date and time when this event occurred')),
                ('event_content', models.TextField(help_text='Content/description of what happened at this time')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the diary entry')),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contents', to='dairyentry.diaryentry')),
            ],
            options={
                'verbose_name_plural': 'Event Contents',
                'ordering': ['diary_entry', 'event_datetime', 'order'],
                'indexes': [models.Index(fields=['diary_entry', 'event_datetime'], name='dairyentry__diary_e_bd8c66_idx'), models.Index(fields=['diary_entry', 'order'], name='dairyentry__diary_e_0ec535_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of this food routine')),
                ('morning_items', models.JSONField(blank=True, help_text='Morning food/drinks: [{name, quantity, time, calories, notes}, ...]', null=True)),
                ('breakfast_items', models.JSONField(blank=True, help_text='Breakfast items: [{name, quantity, time, calories, notes}, ...]', null=True)),
                ('lunch_items', models.JSONField(blank=True, help_text='Lunch items: [{name, quantity, time, calories, notes}, ...]', null=True)),
                ('dinner_items', models.JSONField(blank=True, help_text='Dinner items: [{name, quantity, time, calories, notes}, ...]', null=True)),
                ('snacks', models.JSONField(blank=True, help_text='Snacks throughout the day: [{name, quantity, time, calories, notes}, ...]', null=True)),
                ('water_intake', models.DecimalField(blank=True, decimal_places=2, help_text='Water intake in liters', max_digits=5, null=True)),
                ('total_calories', models.PositiveIntegerField(blank=True, help_text='Estimated total calories for the day', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about food routine', null=True)),
                ('diary_entry', models.OneToOneField(blank=True, help_text='Optional link to diary entry for this day', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_routine', to='dairyentry.diaryentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Food Routines',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='dairyentry__user_id_fa80d9_idx'), models.Index(fields=['date'], name='dairyentry__date_db233b_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
