# Generated by Django 5.0.7 on 2025-10-03 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.JSONField(default=list, help_text='List of keywords to match in transaction references')),
                ('icon', models.CharField(blank=True, help_text='Icon/emoji for UI', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='System-wide default category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this category (null for default categories)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Same as transaction debit', max_digits=12)),
                ('date', models.DateField(help_text='Same as transaction date')),
                ('description', models.TextField(help_text='Cleaned up transaction reference')),
                ('notes', models.TextField(blank=True, help_text="User's custom notes", null=True)),
                ('is_auto_categorized', models.BooleanField(default=False, help_text='Auto-categorized or manually set')),
                ('is_recurring', models.BooleanField(default=False, help_text='Mark if recurring expense')),
                ('tags', models.JSONField(default=list, help_text='Custom tags for filtering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Expense category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.category')),
                ('transaction', models.OneToOneField(help_text='Linked transaction (debit only)', on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='expenses.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_default'], name='expenses_ca_is_defa_79c976_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user'], name='expenses_ca_user_id_95bcba_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expenses_ex_user_id_713a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expenses_ex_categor_20264a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_recurring'], name='expenses_ex_is_recu_dc1876_idx'),
        ),
    ]
