# Generated by Django 5.2.4 on 2025-08-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region_slug',
        ),
    ]
