# Generated by Django 5.2.4 on 2025-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_remove_region_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_slug',
            field=models.SlugField(default='default-slug', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=100),
        ),
    ]
