# Generated by Django 5.2.4 on 2025-08-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_region_region_slug_alter_region_region_name'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='state.state'),
        ),
    ]
