# Generated by Django 5.2.4 on 2025-08-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_approve', 'Can approve Order'), ('can_lock', 'Can lock Order')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_qty',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='amount',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
    ]
