# Generated by Django 5.2.4 on 2025-08-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, unique=True, verbose_name='State Name')),
                ('state_code', models.CharField(max_length=20, verbose_name='State Code')),
            ],
        ),
    ]
